### ISSUE TITLE
LÖVE Loader + Exporter

### ISSUE THREAD

**Issue by Rami-Sabbagh** [CodeAndWeb/PhysicsEditor-Loaders#1]
Hi, I made a loader & exporter for LÖVE, wish if you add them https://github.com/RamiLego4Game/Love2D-PhysicsEditor-Library

**Comment by CodeAndWeb** [comment]
Hi,

I’ve already seen it - awesome! Thanks! 

I’ve never worked with Love2d - would it be easy to create a time demo?

Best
Andreas

**Comment by Rami-Sabbagh** [comment]
Hmm, A time demo ? What do you mean with it ?

**Comment by Rami-Sabbagh** [comment]
I should thank you for giving me a license :)

**Comment by CodeAndWeb** [comment]
Hi,

Hmm, A time demo ? What do you mean with it ?

“time” => “tiny” ;-)

Something simple like this one:
https://www.codeandweb.com/blog/2015/07/15/cocos2d-physics-tutorial https://www.codeandweb.com/blog/2015/07/15/cocos2d-physics-tutorial

Best
Andreas

**Comment by RamiLego4Game** [comment]
Wouldn't it be easy if you used my game ? You can add Phyics editor objects (See the PhysicsEditor tab in the game) http://www.indiedb.com/games/pixelizerbox [download from itch.io link] , Without coding. Or you want a game base for it ?

**Comment by Rami-Sabbagh** [comment]
The demo is ready, check the source, Noe there is new files (main.lua, config.lua, etc)
Also you can download it as a release in a .love file to run with example objects.
If you want to add objects read the top of main.lua

**Comment by Rami-Sabbagh** [comment]
I'm not sure why this didn't get closed
