### ISSUE TITLE
generic-box2d-plist-cocos2d-x not compiles with latest cocos2d-x v3.14

### ISSUE THREAD

**Issue by Anywhere-Music-Player** [CodeAndWeb/PhysicsEditor-Loaders#8]
_generic-box2d-plist-cocos2d-x_ not compiles with latest cocos2d-x v3.14
Should be updated.

**Comment by CodeAndWeb** [comment]
Sorry - can't reproduce on MacOS. Might be related to a name conflict with Polygon class.
I've moved the class inside PhysicsShapeCache. This should fix the compilation on Windows.

Demo project also updated: https://github.com/CodeAndWeb/PhysicsEditor-Cocos2d-x

**Comment by Anywhere-Music-Player** [comment]
As I wrote in first message, I'm talking about 
generic-**box2d**-plist-cocos2d-x

https://github.com/CodeAndWeb/PhysicsEditor-Loaders/blob/master/generic-box2d-plist-cocos2d-x/GB2ShapeCache-x.cpp

Why you close it so fast, without waiting for my reply? Please reopen this issue. You updated loader not for box2d.
